# Generated by Django 5.2.7 on 2025-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_alter_car_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='enginenum',
            field=models.IntegerField(max_length=10),
        ),
    ]
